version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: django-mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: bees_db
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:  # ✅ 추가: db 준비 완료 확인용
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: django-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  # ✅ 수정: db가 healthy 상태일 때 실행
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
