# Generated by Django 5.2.1 on 2025-05-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_create', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invite_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
